import { z } from 'zod';

export const questZodSchema = z.object({
  answers: z.object({
    // Campos obligatorios (solo los que tienen asterisco en el frontend)
    experience: z.string().min(1, "La experiencia es requerida"),
    role: z.string().min(1, "El rol es requerido"),
    'work-mode': z.string().min(1, "El modo de trabajo es requerido"),
    language: z.string().min(1, "El lenguaje principal es requerido"),
    os: z.string().min(1, "El sistema operativo es requerido"),
    editor: z.string().min(1, "El editor es requerido"),
    frameworks: z.array(z.string()).min(1, "Selecciona al menos un framework"),

    // Campos opcionales (pueden estar vacíos o no estar presentes)
    'secondary-languages': z.array(z.string()).optional(),
    'company-size': z.string().optional(),
    'salary-satisfaction': z.string().optional(),
    terminal: z.string().optional(),
    keyboard: z.string().optional(),
    tools: z.array(z.string()).optional(),
    database: z.array(z.string()).optional(),
    'ai-tools': z.array(z.string()).optional(),
    testing: z.array(z.string()).optional(),
    learning: z.string().optional(),
    challenge: z.string().optional(),
    'ai-impact': z.string().optional(),
    'tech-content': z.array(z.string()).optional(),
    wish: z.string().optional(),
    prediction: z.string().optional()
  }),
  submittedAt: z.string().datetime(),
  sessionId: z.string().min(1, "SessionId es requerido"),
  userAgent: z.string().min(1, "UserAgent es requerido"),
  ip: z.string().optional(),
}).transform(({ answers, submittedAt, sessionId, userAgent, ip }) => ({
  sessionId,
  submittedAt: new Date(submittedAt),
  userAgent,
  ip,
  experience: answers.experience,
  role: answers.role,
  work_mode: answers['work-mode'],
  company_size: answers['company-size'],
  salary_satisfaction: answers['salary-satisfaction'],
  language: answers.language,
  secondary_languages: answers['secondary-languages'],
  os: answers.os,
  editor: answers.editor,
  terminal: answers.terminal,
  keyboard: answers.keyboard,
  frameworks: answers.frameworks,
  tools: answers.tools,
  database: answers.database,
  ai_tools: answers['ai-tools'],
  testing: answers.testing,
  learning: answers.learning,
  challenge: answers.challenge,
  ai_impact: answers['ai-impact'],
  tech_content: answers['tech-content'],
  wish: answers.wish,
  prediction: answers.prediction
}));