import { z } from 'zod';

export const questZodSchema = z.object({
  answers: z.object({
    experience: z.string(),
    role: z.string(),
    'work-mode': z.string(),
    'company-size': z.string(),
    'salary-satisfaction': z.string(),
    language: z.string(),
    'secondary-languages': z.array(z.string()),
    os: z.string(),
    editor: z.string(),
    terminal: z.string(),
    keyboard: z.string(),
    frameworks: z.array(z.string()),
    tools: z.array(z.string()),
    database: z.array(z.string()),
    'ai-tools': z.array(z.string()),
    testing: z.array(z.string()),
    learning: z.string().optional(),
    challenge: z.string(),
    'ai-impact': z.string(),
    'tech-content': z.array(z.string()),
    wish: z.string().optional(),
    prediction: z.string().optional()
  }),
  submittedAt: z.string().datetime(),
  sessionId: z.string(),
  userAgent: z.string(),
  ip: z.string().optional(),
}).transform(({ answers, submittedAt, sessionId, userAgent, ip }) => ({
  sessionId,
  submittedAt: new Date(submittedAt),
  userAgent,
  ip,
  experience: answers.experience,
  role: answers.role,
  work_mode: answers['work-mode'],
  company_size: answers['company-size'],
  salary_satisfaction: answers['salary-satisfaction'],
  language: answers.language,
  secondary_languages: answers['secondary-languages'],
  os: answers.os,
  editor: answers.editor,
  terminal: answers.terminal,
  keyboard: answers.keyboard,
  frameworks: answers.frameworks,
  tools: answers.tools,
  database: answers.database,
  ai_tools: answers['ai-tools'],
  testing: answers.testing,
  learning: answers.learning,
  challenge: answers.challenge,
  ai_impact: answers['ai-impact'],
  tech_content: answers['tech-content'],
  wish: answers.wish,
  prediction: answers.prediction
}));